# Generated by Django 3.2.12 on 2023-05-25 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pastquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastquestion',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='pastquestion',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pastquestion',
            name='document',
            field=models.FileField(upload_to='past_questions/'),
        ),
    ]
